version: "3.8"
services:
  # db:
  #   container_name: events-db
  #   image: postgres:12
  #   volumes:
  #     - type: volume
  #       source: postgresdb-data
  #       target: /var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: unanimous
  #     POSTGRES_DB: eventDB
  #     POSTGRES_PASSWORD: password

  main:
    container_name: wood-js-server
    build:
      context: ./APIServer
      dockerfile: Dockerfile

    ports:
      - "8010:8010"
#     depends_on:
#       - db

# volumes:
#   postgresdb-data:
#     driver: local